### ISSUE TITLE
Feature Request: GamePad for dual PC setups 

### ISSUE THREAD

**Issue by 0xjmp** [GamePadViewer/feature-requests#1]
Hi, 

Thank you for building this, its super cool! I really would like to use it for my stream, but I am using a dual PC setup. One PC streams to twitch, the other is dedicated to gaming. 

You can probably already tell what my issue is: my gamepad signal must be received by the gaming pc, where I cannot currently get the gamepad viewer to display _on_ the streaming pc. People online suggested building custom hardware (e.g. arduino) but I don't think that should be necessary...

My idea: allow for gamepadviewer.com to forward signal to a hosted web address instead of displaying in current web browser. This should be straightforward enough assuming access to the actual source code is possible. I recognize that its not currently open-sourced and you may feel hesitant to give others access, which is okay with me. Although, I have a decade of experience coding a plethora of languages, and would be more than happy to help out with this if that would pique your interest in making this feature a reality.

I know this is a need because a Google search of "Gamepadviewer for dual pc" shows several forums where people are asking for exactly this. What they don't realize is this - in theory - should be possible without any dedicated hardware!

Thank you for taking the time to consider this idea. If I can put together an albeit hacky solution before I hear from you, I will be sure to share how I did it. Cheers!

**Comment by Jayraydee** [comment]
Good news! We already have a working methodology for this using NDI over your local network!  
Pasted below is the bot info from the support discord:

GPV Support Archives
Dual PC Streaming Setup
In order to show your controller inputs on a dual pc stream setup, you'll need OBS installed on both PC's. After getting OBS you will need to download the OBS NDI plugin found here:
https://github.com/Palakis/obs-ndi/releases
Follow this tutorial to set it up:
https://www.youtube.com/watch?v=SEJPEFu4JUg

Once set up, simply send the controller inputs send from the gaming computer's OBS to the streaming computer's OBS. You should then be able to resize it and be good to go!
If you need further assistance feel free to ask in the #support channel

**Comment by 0xjmp** [comment]
Oh man that's genius! Totally worked right away. Thank you so much!
